### ISSUE TITLE
Integration test race condition can make the tests fail

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1624]
https://apm-ci.elastic.co/job/elastic+apm-server+pull-request+multijob-linux/beat=apm-server,label=ubuntu/180/console

```
13:17:46 command [go test -race -tags integration -cover -coverprofile /tmp/gotestcover-888627635 github.com/elastic/apm-server/beater]: exit status 1
13:17:46 2018/12/05 13:17:15 http: TLS handshake error from 127.0.0.1:54304: remote error: tls: bad certificate
13:17:46 2018/12/05 13:17:16 http: TLS handshake error from 127.0.0.1:49550: remote error: tls: bad certificate
13:17:46 [1Bmake: *** [integration-tests] Error 1
13:17:46 2018/12/05 13:17:17 http: TLS handshake error from 127.0.0.1:33896: remote error: tls: bad certificate
13:17:46 2018/12/05 13:17:17 http: TLS handshake error from 127.0.0.1:48310: tls: oversized record received with length 21536
13:17:46 --- FAIL: TestServerSecureBadPassphrase (26.74s)
13:17:46     server_test.go:557: generating certificate in /go/src/github.com/elastic/apm-server/beater/test_certs/TestServerSecureBadPassphrase
13:17:46 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
13:17:46 	panic: runtime error: invalid memory address or nil pointer dereference
13:17:46 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x101ece4]
13:17:46 
13:17:46 goroutine 55681 [running]:
13:17:46 testing.tRunner.func1(0xc00073b700)
13:17:46 	/usr/local/go/src/testing/testing.go:792 +0x6a7
13:17:46 panic(0x113c1c0, 0x1ac4090)
13:17:46 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
13:17:46 github.com/elastic/apm-server/beater.(*beater).client(0xc000289020, 0x130ed01, 0x0, 0x0, 0x0)
13:17:46 	/go/src/github.com/elastic/apm-server/beater/beater_test.go:371 +0x134
13:17:46 github.com/elastic/apm-server/beater.setupBeater(0xc00073b700, 0x1319700, 0xc00026a000, 0xc0004fdc80, 0x0, 0x0, 0x0, 0x884801, 0xc00073b700)
13:17:46 	/go/src/github.com/elastic/apm-server/beater/beater_test.go:456 +0x3e3
13:17:46 github.com/elastic/apm-server/beater.setupServer(0xc00073b700, 0xc0005a0180, 0x0, 0x0, 0x0, 0x0, 0x0)
13:17:46 	/go/src/github.com/elastic/apm-server/beater/server_test.go:532 +0x20b
13:17:46 github.com/elastic/apm-server/beater.TestServerSecureBadPassphrase(0xc00073b700)
13:17:46 	/go/src/github.com/elastic/apm-server/beater/server_test.go:510 +0x4c1
13:17:46 testing.tRunner(0xc00073b700, 0x1242fd8)
13:17:46 	/usr/local/go/src/testing/testing.go:827 +0x163
13:17:46 created by testing.(*T).Run
13:17:46 	/usr/local/go/src/testing/testing.go:878 +0x651
13:17:46 FAIL	github.com/elastic/apm-server/beater	104.457s
```

**Comment by graphaelli** [comment]
closed by #2224
