### ISSUE TITLE
apm.(*Tracer).Close panic

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1754]
Running into this panic while working on integration tests:

```
panic: close of closed channel

goroutine 67 [running]:
github.com/elastic/apm-server/vendor/go.elastic.co/apm.(*Tracer).Close(0xc000154000)
	go/src/github.com/elastic/apm-server/vendor/go.elastic.co/apm/tracer.go:306 +0xc9
github.com/elastic/apm-server/beater.initTracer(0x4b0c102, 0xf, 0x4b0c102, 0xf, 0x4b06eb7, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
	go/src/github.com/elastic/apm-server/beater/beater.go:176 +0x63
github.com/elastic/apm-server/beater.(*beater).Run(0xc000330870, 0xc00036c000, 0x0, 0x0)
	go/src/github.com/elastic/apm-server/beater/beater.go:125 +0x10f
```

Appears to be related to the recent elastic/apm-server#1738 change.

**Comment by axw** [comment]
Maybe move the DefualtTracer.Close() to a package init func? In normal operation initTracer will never be called multiple times, right?
