### ISSUE TITLE
Fix flaky APIKeyTest test_invalidate_by_id

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3298]
Looks like there is a new flaky test showing up:

**Build and Test / System and Environment Tests / test_apikey.APIKeyTest.test_invalidate_by_id** (from nosetests)

**Error Message**
```
{u'invalidated_api_keys': [], u'error_count': 0}
```

**Stacktrace**
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/go/src/github.com/elastic/apm-server/tests/system/test_apikey.py", line 90, in test_invalidate_by_id
    assert invalidated.get("invalidated_api_keys") == [apikey["id"]], invalidated
AssertionError: {u'invalidated_api_keys': [], u'error_count': 0}
```

**Comment by jalvz** [comment]
`./apm-server apikey create -E apm-server.api_key.elasticsearch.username=admin -E apm-server.api_key.elasticsearch.password=changeme` fails locally for me, can you reproduce?

`git bisect` points to 55e407838017a12ad873603432ce24c2d65b466d

**Comment by simitt** [comment]
In which scenario does above mentioned cmd fail locally? (How did you start the environment?)

**Comment by jalvz** [comment]
I think any, you don't even need a connection. Well, I mean _I_ didn't even need a connection...
Not saying that the test is not flaky neither; maybe there are several things at play.

**Comment by simitt** [comment]
Another test was failing where an API Key that should have been invalidated, wasn't. This might be related:

```
[2020-02-20T18:59:28.373Z] ======================================================================

[2020-02-20T18:59:28.373Z] FAIL: test_info_by_name (test_apikey.APIKeyTest)

[2020-02-20T18:59:28.373Z] ----------------------------------------------------------------------

[2020-02-20T18:59:28.373Z] Traceback (most recent call last):

[2020-02-20T18:59:28.373Z]   File "/go/src/github.com/elastic/apm-server/tests/system/test_apikey.py", line 122, in test_info_by_name

[2020-02-20T18:59:28.373Z]     assert len(info.get("api_keys")) == 2, info

[2020-02-20T18:59:28.373Z] AssertionError: {u'api_keys': [{u'username': u'apm_server_user', u'creation': 1582224716534, u'id': u'-WDxY3ABE8Fs4UHRM0IL', u'invalidated': False, u'name': u'apm_integration_key'}, {u'username': u'apm_server_user', u'creation': 1582224717693, u'id': u'-mDxY3ABE8Fs4UHRN0Ke', u'invalidated': False, u'name': u'apm_integration_key'}, {u'username': u'apm_server_user', u'creation': 1582224718607, u'id': u'-2DxY3ABE8Fs4UHRO0Iu', u'invalidated': False, u'name': u'apm_integration_key'}]}

```

**Comment by simitt** [comment]
Recent test changes should allow to observe where exactly the issue lies - in creating or invalidating API Keys. Putting the issue into `blocked` state until the next test failure occurs.

**Comment by simitt** [comment]
The test failure happened again, and by analyzing the artifacts I was able to pin the failure to API Keys where the ID starts with a `-`. 

When an argument value starts with a dash it needs to be properly escaped, otherwise it will end up starting with two dashes, e.g. `-xyz` would be interpreted as `--xyz`. 
Instead of running `./apm-server apikey info --id -DB06HAB0_bchW-gz4zt` it should be  run as `./apm-server apikey info --id="-DB06HAB0_bchW-gz4zt"`
