### ISSUE TITLE
test_trace_ids: unterminated string

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3353]
Spotted once for now, lets keep an eye on it:

```
[2020-02-18T09:58:18.362Z] ERROR: test_trace_ids (test_integration_logging.LoggingIntegrationTraceCorrelationTest)
[2020-02-18T09:58:18.362Z] ----------------------------------------------------------------------
[2020-02-18T09:58:18.362Z] Traceback (most recent call last):
[2020-02-18T09:58:18.362Z]   File "/go/src/github.com/elastic/apm-server/tests/system/test_integration_logging.py", line 86, in test_trace_ids
[2020-02-18T09:58:18.362Z]     intake_request_logs = list(self.logged_requests())
[2020-02-18T09:58:18.362Z]   File "/go/src/github.com/elastic/apm-server/tests/system/apmserver.py", line 339, in logged_requests
[2020-02-18T09:58:18.362Z]     jline = json.loads(line)
[2020-02-18T09:58:18.362Z]   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
[2020-02-18T09:58:18.362Z]     return _default_decoder.decode(s)
[2020-02-18T09:58:18.362Z]   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
[2020-02-18T09:58:18.362Z]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2020-02-18T09:58:18.362Z]   File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
[2020-02-18T09:58:18.362Z]     obj, end = self.scan_once(s, idx)
[2020-02-18T09:58:18.362Z] ValueError: Unterminated string starting at: line 1 column 129 (char 128)
[2020-02-18T09:58:18.362Z] -------------------- >> begin captured logging << --------------------
```

https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/branches/PR-3348/runs/1/nodes/175/steps/209/log/?start=0

**Comment by axw** [comment]
I saw this again recently. Rather than spend time fixing it, I've added the test to https://github.com/elastic/apm-server/pull/3790.
