### ISSUE TITLE
[test] Flaky TLS system test

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3420]
There is a new flaky system test, probably related with the changes introduced when switching to python3:

`test_tls.TestSSLEnabledNoClientVerificationTest.test_http_fails`

**Error Message**

Exception not raised

**Stacktrace**
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/go/src/github.com/elastic/apm-server/tests/system/test_tls.py", line 109, in test_http_fails
    data=self.get_event_payload())
  File "/usr/lib/python3.7/unittest/case.py", line 203, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/usr/lib/python3.7/unittest/case.py", line 135, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: Exception not raised

```

**Comment by simitt** [comment]
The test can be run locally by `make system-tests SYSTEM_TEST_TARGET=./tests/system/test_tls.py:TestSSLEnabledNoClientVerificationTest.test_http_fails`

cc @mdelapenya

**Comment by mdelapenya** [comment]
As we discussed today, it seems that the requests library is reusing connections from its internal pool. We agreed in simplifying the test (maybe a simple GET request to the root path `http:/localhost:8200/` would be enough)

**Comment by mdelapenya** [comment]
More investigation:

Reverting back to the original test, using the HttpSession:
```python
    def test_http_fails(self):
        with self.assertRaises(Exception):
            with requests.Session() as session:
                try:
                    session.headers.update({"Connection": "close"})
                    return session.get("http://localhost:8200")
                finally:
                    session.close()
```
the test result is:
```
======================================================================
FAIL: test_http_fails (test_tls.TestSSLEnabledNoClientVerificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/src/apm-server/tests/system/test_tls.py", line 115, in test_http_fails
    session.close()
AssertionError: Exception not raised
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8200
urllib3.connectionpool: DEBUG: http://localhost:8200 "GET / HTTP/1.1" 400 None
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
XML: /src/apm-server/build/TEST-system.xml
[fail] 100.00% test_tls.TestSSLEnabledNoClientVerificationTest.test_http_fails: 0.9465s
----------------------------------------------------------------------
Ran 1 test in 1.378s
FAILED (failures=1)
```
Sharing this results with @beniwohli, we see that APM Server returns a 400 Bad Request when doing an http request with TLS enabled. @simitt is that correct? Do we want to capture that HTTP return code?
