### ISSUE TITLE
[test] Fix flaky system test for TestTransactionAggregationShutdown

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4366]
The system test `TestTransactionAggregationShutdown` failed on `master` branch:

```
[2020-10-29T12:54:38.329Z] === RUN   TestTransactionAggregationShutdown

[2020-10-29T12:54:38.329Z] panic: test timed out after 10m0s

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 165 [running]:

[2020-10-29T12:54:38.329Z] testing.(*M).startAlarm.func1()

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1509 +0xdf

[2020-10-29T12:54:38.329Z] created by time.goFunc

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/time/sleep.go:168 +0x44

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 1 [chan receive, 9 minutes]:

[2020-10-29T12:54:38.329Z] testing.(*T).Run(0xc000afa120, 0x114973d, 0x22, 0x1168408, 0x4c9e01)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1091 +0x399

[2020-10-29T12:54:38.329Z] testing.runTests.func1(0xc000108ea0)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1334 +0x78

[2020-10-29T12:54:38.329Z] testing.tRunner(0xc000108ea0, 0xc00039fdd8)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1039 +0xdc

[2020-10-29T12:54:38.329Z] testing.runTests(0xc00051d000, 0x1ca0f20, 0x13, 0x13, 0x0)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1332 +0x2a7

[2020-10-29T12:54:38.329Z] testing.(*M).Run(0xc000130000, 0x0)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1249 +0x1b7

[2020-10-29T12:54:38.329Z] github.com/elastic/apm-server/systemtest.TestMain(0xc000130000)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/src/github.com/elastic/apm-server/systemtest/main_test.go:30 +0x76

[2020-10-29T12:54:38.329Z] main.main()

[2020-10-29T12:54:38.329Z] 	_testmain.go:80 +0x135

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 11 [select]:

[2020-10-29T12:54:38.329Z] go.elastic.co/apm.(*Tracer).loop(0xc0001fa900)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/tracer.go:873 +0xb28

[2020-10-29T12:54:38.329Z] created by go.elastic.co/apm.newTracer

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/tracer.go:433 +0x7cc

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 12 [select]:

[2020-10-29T12:54:38.329Z] go.elastic.co/apm/transport/transporttest.ErrorTransport.SendStream(0x0, 0x0, 0x12bab40, 0xc000033d40, 0x12a3e00, 0xc0005be8c0, 0xccf301, 0x101)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/transport/transporttest/err.go:45 +0x123

[2020-10-29T12:54:38.329Z] go.elastic.co/apm.(*Tracer).loop.func2(0xc000518720, 0xc0005186c0, 0x12bab40, 0xc000033d40, 0xc0004f0780, 0xc0001fa900, 0xc00001c770)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/tracer.go:783 +0x1d0

[2020-10-29T12:54:38.329Z] created by go.elastic.co/apm.(*Tracer).loop

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/tracer.go:773 +0x36e

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 99 [sleep]:

[2020-10-29T12:54:38.329Z] time.Sleep(0x5f5e100)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/runtime/time.go:188 +0xba

[2020-10-29T12:54:38.329Z] github.com/elastic/apm-server/systemtest.CleanupElasticsearch(0x12cdb60, 0xc000afa120)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/src/github.com/elastic/apm-server/systemtest/elasticsearch.go:124 +0x319

[2020-10-29T12:54:38.329Z] github.com/elastic/apm-server/systemtest_test.TestTransactionAggregationShutdown(0xc000afa120)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/src/github.com/elastic/apm-server/systemtest/aggregation_test.go:85 +0x4f

[2020-10-29T12:54:38.329Z] testing.tRunner(0xc000afa120, 0x1168408)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1039 +0xdc

[2020-10-29T12:54:38.329Z] created by testing.(*T).Run

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/testing/testing.go:1090 +0x372

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 115 [select]:

[2020-10-29T12:54:38.329Z] net/http.(*persistConn).writeLoop(0xc000c8c000)

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/http/transport.go:2277 +0x11c

[2020-10-29T12:54:38.329Z] created by net/http.(*Transport).dialConn

[2020-10-29T12:54:38.329Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/http/transport.go:1648 +0xc7b

[2020-10-29T12:54:38.329Z] 

[2020-10-29T12:54:38.329Z] goroutine 48 [select, 9 minutes]:

[2020-10-29T12:54:38.330Z] io.(*pipe).Write(0xc00051b260, 0xc000b9c000, 0x1, 0x8000, 0x0, 0x0, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/pipe.go:94 +0x1db

[2020-10-29T12:54:38.330Z] io.(*PipeWriter).Write(0xc000010490, 0xc000b9c000, 0x1, 0x8000, 0x1, 0x0, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/pipe.go:163 +0x4c

[2020-10-29T12:54:38.330Z] io.copyBuffer(0x12a4440, 0xc000010490, 0x12a4460, 0xc000ae81a0, 0xc000b9c000, 0x8000, 0x8000, 0x2, 0x10, 0x1c7)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/io.go:407 +0x1fb

[2020-10-29T12:54:38.330Z] io.Copy(...)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/io.go:364

[2020-10-29T12:54:38.330Z] github.com/elastic/apm-server/systemtest/apmservertest.(*Server).consumeStderr(0xc0001fb800, 0x12a44a0, 0xc00029fac0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/src/github.com/elastic/apm-server/systemtest/apmservertest/server.go:334 +0x6d1

[2020-10-29T12:54:38.330Z] github.com/elastic/apm-server/systemtest/apmservertest.(*Server).Start.func4(0xc000010480, 0xc0001fb800, 0x12afd40, 0xc000010458)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/src/github.com/elastic/apm-server/systemtest/apmservertest/server.go:183 +0xec

[2020-10-29T12:54:38.330Z] created by github.com/elastic/apm-server/systemtest/apmservertest.(*Server).Start

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/src/github.com/elastic/apm-server/systemtest/apmservertest/server.go:181 +0x88e

[2020-10-29T12:54:38.330Z] 

[2020-10-29T12:54:38.330Z] goroutine 114 [IO wait]:

[2020-10-29T12:54:38.330Z] internal/poll.runtime_pollWait(0x7fdf9456f628, 0x72, 0xffffffffffffffff)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/runtime/netpoll.go:203 +0x55

[2020-10-29T12:54:38.330Z] internal/poll.(*pollDesc).wait(0xc000318518, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x45

[2020-10-29T12:54:38.330Z] internal/poll.(*pollDesc).waitRead(...)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/internal/poll/fd_poll_runtime.go:92

[2020-10-29T12:54:38.330Z] internal/poll.(*FD).Read(0xc000318500, 0xc000c8e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/internal/poll/fd_unix.go:169 +0x19b

[2020-10-29T12:54:38.330Z] net.(*netFD).Read(0xc000318500, 0xc000c8e000, 0x1000, 0x1000, 0x43949c, 0xc00006db70, 0x465880)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/fd_unix.go:202 +0x4f

[2020-10-29T12:54:38.330Z] net.(*conn).Read(0xc000010070, 0xc000c8e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/net.go:184 +0x8e

[2020-10-29T12:54:38.330Z] net/http.(*persistConn).Read(0xc000c8c000, 0xc000c8e000, 0x1000, 0x1000, 0xc0002a0000, 0xc00006dc70, 0x406ed5)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/http/transport.go:1825 +0x75

[2020-10-29T12:54:38.330Z] bufio.(*Reader).fill(0xc000c8a420)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/bufio/bufio.go:100 +0x103

[2020-10-29T12:54:38.330Z] bufio.(*Reader).Peek(0xc000c8a420, 0x1, 0x0, 0x0, 0x1, 0xc0002a1000, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/bufio/bufio.go:138 +0x4f

[2020-10-29T12:54:38.330Z] net/http.(*persistConn).readLoop(0xc000c8c000)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/http/transport.go:1978 +0x1a8

[2020-10-29T12:54:38.330Z] created by net/http.(*Transport).dialConn

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/net/http/transport.go:1647 +0xc56

[2020-10-29T12:54:38.330Z] 

[2020-10-29T12:54:38.330Z] goroutine 142 [chan receive]:

[2020-10-29T12:54:38.330Z] go.elastic.co/apm/internal/iochan.(*Reader).Read(0xc0005be8c0, 0xc0004ce000, 0x2000, 0x2000, 0x2f4, 0x0, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/internal/iochan/reader.go:87 +0x135

[2020-10-29T12:54:38.330Z] io/ioutil.devNull.ReadFrom(0x0, 0x12a3e00, 0xc0005be8c0, 0xff8da0, 0xc000001e01, 0x7fdf955ef1f0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/ioutil/ioutil.go:144 +0x92

[2020-10-29T12:54:38.330Z] io.copyBuffer(0x12a55c0, 0x1d23fd0, 0x12a3e00, 0xc0005be8c0, 0x0, 0x0, 0x0, 0xc000518780, 0xc00035b7a0, 0x0)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/io.go:391 +0x2fc

[2020-10-29T12:54:38.330Z] io.Copy(...)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/.gvm/versions/go1.14.7.linux.amd64/src/io/io.go:364

[2020-10-29T12:54:38.330Z] go.elastic.co/apm/transport/transporttest.ErrorTransport.SendStream.func1(0x12a3e00, 0xc0005be8c0, 0xc00023a900)

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/transport/transporttest/err.go:42 +0x67

[2020-10-29T12:54:38.330Z] created by go.elastic.co/apm/transport/transporttest.ErrorTransport.SendStream

[2020-10-29T12:54:38.330Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-4363/pkg/mod/go.elastic.co/apm@v1.8.1-0.20200913025752-7af7e1529586/transport/transporttest/err.go:41 +0x89

[2020-10-29T12:54:38.330Z] FAIL	github.com/elastic/apm-server/systemtest	601.225s

```

**Comment by axw** [comment]
Ahh, interesting -- it's timing out in `systemtest.CleanupElasticsearch`. This means that we're failing to delete the ILM policy in 10 minutes. I've yet to reproduce the issue locally so far.

**Comment by simitt** [comment]
Just saw it happening again https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-4397/1/pipeline/

**Comment by simitt** [comment]
It looks like some existing indices are using the ILM policies, preventing them from being deleted. I assume some other test doesn't properly clean up behind itself. 

```
[2020-11-16T13:54:46.112Z] === RUN   TestTransactionAggregationShutdown
[2020-11-16T13:54:46.112Z]     elasticsearch.go:125: failed to delete ILM policy (retrying in 100ms): [400 Bad Request] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Cannot delete policy [apm-rollover-30-days]. It is in use by one or more indices: [apm-8.0.0-profile-000001]"}],"type":"illegal_argument_exception","reason":"Cannot delete policy [apm-rollover-30-days]. It is in use by one or more indices: [apm-8.0.0-profile-000001]"},"status":400}
```

**Comment by axw** [comment]
I've put up https://github.com/elastic/apm-server/pull/4431 to repeat the index deletions if ILM policy cannot be deleted. I was hoping not to be this heavy-handed, as it could mask issues/poorly written tests.

I guess this is a visibility issue which might be resolvable by adding a `POST /_refresh`, but I'll just do the simple thing for now so we can address the test flakiness.

**Comment by axw** [comment]
Still happening: https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/branches/PR-4449/runs/14/nodes/139/steps/247/log/?start=0

**Comment by simitt** [comment]
seeing this again in the last days https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/branches/PR-4569/runs/1/nodes/144/steps/242/log/?start=0

**Comment by simitt** [comment]
our friend is back https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/branches/PR-4675/runs/2/nodes/152/steps/262/log/?start=0
