### ISSUE TITLE
Race when starting APM Server on a used port

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#466]
When starting APM Server on a port that is already in use, it will occasionally `panic: send on closed channel` instead of the intended message 

```
2018-01-10T13:14:42.170+0100	ERROR	instance/beat.go:666	Exiting: listen tcp 127.0.0.1:8200: bind: address already in use
Exiting: listen tcp 127.0.0.1:8200: bind: address already in use
```

Full output:

```$ ./apm-server -e
2018-01-10T13:14:40.812+0100	INFO	instance/beat.go:467	Home path: [/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server] Config path: [/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server] Data path: [/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server/data] Logs path: [/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server/logs]
2018-01-10T13:14:40.812+0100	INFO	instance/beat.go:474	Beat UUID: 999256f1-bc70-4224-86d0-1bf6891a9d6c
2018-01-10T13:14:40.812+0100	INFO	instance/beat.go:212	Setup Beat: apm-server; Version: 7.0.0-alpha1
2018-01-10T13:14:40.812+0100	INFO	elasticsearch/client.go:123	Elasticsearch url: http://localhost:9200
2018-01-10T13:14:40.813+0100	INFO	pipeline/module.go:76	Beat name: VeryFastPicket.local
2018-01-10T13:14:40.813+0100	INFO	instance/beat.go:300	apm-server start running.
2018-01-10T13:14:40.813+0100	INFO	[monitoring]	log/log.go:87	Starting metrics logging every 30s
2018-01-10T13:14:40.813+0100	INFO	beater/handlers.go:79	Path /v1/transactions added to request handler
2018-01-10T13:14:40.813+0100	INFO	beater/handlers.go:79	Path /v1/client-side/transactions added to request handler
2018-01-10T13:14:40.813+0100	INFO	beater/handlers.go:79	Path /v1/errors added to request handler
2018-01-10T13:14:40.813+0100	INFO	beater/handlers.go:79	Path /v1/client-side/errors added to request handler
2018-01-10T13:14:40.813+0100	INFO	beater/handlers.go:79	Path /healthcheck added to request handler
2018-01-10T13:14:40.813+0100	INFO	beater/handlers.go:79	Path /v1/client-side/sourcemaps added to request handler
2018-01-10T13:14:40.813+0100	INFO	beater/server.go:28	Starting apm-server [13a5eb8577ec7968a3d814b4ee7030f7aae1a57a built 2018-01-10T12:14:28Z]. Hit CTRL-C to stop it.
2018-01-10T13:14:40.813+0100	INFO	beater/server.go:29	Listening on: localhost:8200
2018-01-10T13:14:40.813+0100	INFO	beater/server.go:34	Frontend endpoints disabled
2018-01-10T13:14:40.815+0100	INFO	instance/beat.go:307	apm-server stopped.
2018-01-10T13:14:40.816+0100	INFO	beater/client.go:32	HTTP Server ready
2018-01-10T13:14:40.820+0100	INFO	beater/onboarding.go:19	Publishing onboarding document
panic: send on closed channel

goroutine 59 [running]:
github.com/elastic/apm-server/beater.(*publisher).Send(0xc420125c80, 0xc4201e80c0, 0x1, 0x1, 0xc420290301, 0xc4201e80c0)
	/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server/beater/pub.go:74 +0x111
github.com/elastic/apm-server/beater.(*publisher).Send-fm(0xc4201e80c0, 0x1, 0x1, 0x9, 0xc4202903e8)
	/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server/beater/beater.go:43 +0x48
github.com/elastic/apm-server/beater.notifyListening(0xc4204a82d0, 0xe, 0x3200000, 0x100000, 0x77359400, 0x77359400, 0x12a05f200, 0x0, 0x0, 0x0, ...)
	/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server/beater/onboarding.go:26 +0x266
created by github.com/elastic/apm-server/beater.(*beater).Run
	/Users/ron/Projects/elastic/goapps/src/github.com/elastic/apm-server/beater/beater.go:43 +0x131```

**Comment by graphaelli** [comment]
6.2 Currently looks like: https://github.com/elastic/apm-server/blob/29d6a287e4953d47cff7c405248858dbeb71e784/beater/beater.go#L41-L52

when `run` on line 47 fails to open a listener on an in use address the function ends and the defered `pub.Stop()` from line 41 fires.  If that is scheduled before `notifyListening`'s `pub.Send` happens then the channel will be closed before the write is attempted.

One quick idea for making this far less likely is to prevent `notifyListening` from even running if the server can't start.  The main reason it can't start is if it can't listen.  Code incoming shortly.

**Comment by graphaelli** [comment]
closing this since most of a fix is in place
