### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by drnextgis** [elastic/apm-server#5114]
I've cloned the repo and trying to run apm-server:

```
$ docker-compose up beat 
Creating network "apm-server_default" with the default driver
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT)...
8.0.0-SNAPSHOT: Pulling from elasticsearch/elasticsearch
e64c22dbcaa2: Pull complete
ac279e011c0c: Pull complete
db0b2d51ae5f: Pull complete
bf02de1264c0: Pull complete
4917313e35c9: Pull complete
Digest: sha256:e4f13c7ef3b58009c2267f2f6128938df612227fa0a3e371d5dbd41bfb4d58fd
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT
Pulling package-registry (docker.elastic.co/package-registry/distribution:snapshot)...
snapshot: Pulling from package-registry/distribution
2d473b07cdd5: Pull complete
2db059bb4584: Pull complete
7f8747a17039: Pull complete
bef928362780: Pull complete
8222ef757e60: Pull complete
3c6edda8daf3: Pull complete
91ca5603195d: Pull complete
69a8bbb606b5: Pull complete
Digest: sha256:a111a280503e6a8050302f939b2f8c9e00e1a18cfed6347eab05564bb34f8bba
Status: Downloaded newer image for docker.elastic.co/package-registry/distribution:snapshot
Pulling kibana (docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT)...
8.0.0-SNAPSHOT: Pulling from kibana/kibana
ddf49b9115d7: Pull complete
5800d3d2be60: Pull complete
e6821bdaa4b7: Pull complete
2e2b9db25332: Pull complete
6b25a440ad20: Pull complete
2816d02373e0: Pull complete
52070477f073: Pull complete
5bae1ab89b5f: Pull complete
20fec15ad208: Pull complete
b395ca15bc7c: Pull complete
f8ab2c87ded6: Pull complete
ecf0f1e7c7cc: Pull complete
a0510eb96ea6: Pull complete
Digest: sha256:c60170865c8eb8f2f32daf7b3be1c1b6f2f7d9cf6176de523817f038cd6303cf
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
Pulling proxy_dep (busybox:)...
latest: Pulling from library/busybox
f531cdc67389: Pull complete
Digest: sha256:ae39a6f5c07297d7ab64dbd4f82c77c874cc6a94cea29fdec309d0992574b4f7
Status: Downloaded newer image for busybox:latest
Building beat
Step 1/23 : FROM golang:1.15.9
1.15.9: Pulling from library/golang
0ecb575e629c: Pull complete
7467d1831b69: Pull complete
feab2c490a3c: Pull complete
f15a0f46f8c3: Pull complete
2ea92ed63b96: Pull complete
e727087cf428: Pull complete
d628d115b11f: Pull complete
Digest: sha256:e1d90e2be8a4fa1a5aeb5095898d93eade9d1e20f8bc1431f5f72b3ab3086708
Status: Downloaded newer image for golang:1.15.9
 ---> 7ab2ba72cb2d
Step 2/23 : MAINTAINER Nicolas Ruflin <ruflin@elastic.co>
 ---> Running in c5b577a66cd8
Removing intermediate container c5b577a66cd8
 ---> a74d1f8fd1f7
Step 3/23 : RUN apt-get update
 ---> Running in 9b8f073f3a41
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [272 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [9504 B]
Fetched 8427 kB in 3s (2420 kB/s)
Reading package lists...
Removing intermediate container 9b8f073f3a41
 ---> 64d24966459b
Step 4/23 : RUN apt-get install -y --no-install-recommends netcat python3 python3-pip python3-venv
 ---> Running in 3a02c51e19bf
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libmpdec2 libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib
  netcat-traditional python-pip-whl python3-distutils python3-lib2to3
  python3-minimal python3.7 python3.7-minimal python3.7-venv
Suggested packages:
  python3-doc python3-tk python3.7-doc binfmt-support
Recommended packages:
  build-essential python3-dev python3-setuptools python3-wheel
The following NEW packages will be installed:
  libmpdec2 libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib netcat
  netcat-traditional python-pip-whl python3 python3-distutils python3-lib2to3
  python3-minimal python3-pip python3-venv python3.7 python3.7-minimal
  python3.7-venv
0 upgraded, 16 newly installed, 0 to remove and 17 not upgraded.
Need to get 6658 kB of archives.
After this operation, 27.2 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libpython3.7-minimal amd64 3.7.3-2+deb10u3 [589 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 python3.7-minimal amd64 3.7.3-2+deb10u3 [1737 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 python3-minimal amd64 3.7.3-1 [36.6 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 libmpdec2 amd64 2.4.2-2 [87.2 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 libpython3.7-stdlib amd64 3.7.3-2+deb10u3 [1734 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 python3.7 amd64 3.7.3-2+deb10u3 [330 kB]
Get:7 http://deb.debian.org/debian buster/main amd64 libpython3-stdlib amd64 3.7.3-1 [20.0 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 python3 amd64 3.7.3-1 [61.5 kB]
Get:9 http://deb.debian.org/debian buster/main amd64 netcat-traditional amd64 1.10-41.1 [66.9 kB]
Get:10 http://deb.debian.org/debian buster/main amd64 netcat all 1.10-41.1 [9034 B]
Get:11 http://deb.debian.org/debian buster/main amd64 python-pip-whl all 18.1-5 [1591 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 python3-lib2to3 all 3.7.3-1 [76.7 kB]
Get:13 http://deb.debian.org/debian buster/main amd64 python3-distutils all 3.7.3-1 [142 kB]
Get:14 http://deb.debian.org/debian buster/main amd64 python3-pip all 18.1-5 [171 kB]
Get:15 http://deb.debian.org/debian buster/main amd64 python3.7-venv amd64 3.7.3-2+deb10u3 [6148 B]
Get:16 http://deb.debian.org/debian buster/main amd64 python3-venv amd64 3.7.3-1 [1180 B]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 6658 kB in 2s (3406 kB/s)
Selecting previously unselected package libpython3.7-minimal:amd64.
(Reading database ... 15421 files and directories currently installed.)
Preparing to unpack .../libpython3.7-minimal_3.7.3-2+deb10u3_amd64.deb ...
Unpacking libpython3.7-minimal:amd64 (3.7.3-2+deb10u3) ...
Selecting previously unselected package python3.7-minimal.
Preparing to unpack .../python3.7-minimal_3.7.3-2+deb10u3_amd64.deb ...
Unpacking python3.7-minimal (3.7.3-2+deb10u3) ...
Setting up libpython3.7-minimal:amd64 (3.7.3-2+deb10u3) ...
Setting up python3.7-minimal (3.7.3-2+deb10u3) ...
Selecting previously unselected package python3-minimal.
(Reading database ... 15661 files and directories currently installed.)
Preparing to unpack .../python3-minimal_3.7.3-1_amd64.deb ...
Unpacking python3-minimal (3.7.3-1) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../libmpdec2_2.4.2-2_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-2) ...
Selecting previously unselected package libpython3.7-stdlib:amd64.
Preparing to unpack .../libpython3.7-stdlib_3.7.3-2+deb10u3_amd64.deb ...
Unpacking libpython3.7-stdlib:amd64 (3.7.3-2+deb10u3) ...
Selecting previously unselected package python3.7.
Preparing to unpack .../python3.7_3.7.3-2+deb10u3_amd64.deb ...
Unpacking python3.7 (3.7.3-2+deb10u3) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../libpython3-stdlib_3.7.3-1_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.7.3-1) ...
Setting up python3-minimal (3.7.3-1) ...
Selecting previously unselected package python3.
(Reading database ... 16073 files and directories currently installed.)
Preparing to unpack .../0-python3_3.7.3-1_amd64.deb ...
Unpacking python3 (3.7.3-1) ...
Selecting previously unselected package netcat-traditional.
Preparing to unpack .../1-netcat-traditional_1.10-41.1_amd64.deb ...
Unpacking netcat-traditional (1.10-41.1) ...
Selecting previously unselected package netcat.
Preparing to unpack .../2-netcat_1.10-41.1_all.deb ...
Unpacking netcat (1.10-41.1) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../3-python-pip-whl_18.1-5_all.deb ...
Unpacking python-pip-whl (18.1-5) ...
Selecting previously unselected package python3-lib2to3.
Preparing to unpack .../4-python3-lib2to3_3.7.3-1_all.deb ...
Unpacking python3-lib2to3 (3.7.3-1) ...
Selecting previously unselected package python3-distutils.
Preparing to unpack .../5-python3-distutils_3.7.3-1_all.deb ...
Unpacking python3-distutils (3.7.3-1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../6-python3-pip_18.1-5_all.deb ...
Unpacking python3-pip (18.1-5) ...
Selecting previously unselected package python3.7-venv.
Preparing to unpack .../7-python3.7-venv_3.7.3-2+deb10u3_amd64.deb ...
Unpacking python3.7-venv (3.7.3-2+deb10u3) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../8-python3-venv_3.7.3-1_amd64.deb ...
Unpacking python3-venv (3.7.3-1) ...
Setting up netcat-traditional (1.10-41.1) ...
update-alternatives: using /bin/nc.traditional to provide /bin/nc (nc) in auto mode
Setting up netcat (1.10-41.1) ...
Setting up python-pip-whl (18.1-5) ...
Setting up libmpdec2:amd64 (2.4.2-2) ...
Setting up libpython3.7-stdlib:amd64 (3.7.3-2+deb10u3) ...
Setting up libpython3-stdlib:amd64 (3.7.3-1) ...
Setting up python3.7 (3.7.3-2+deb10u3) ...
Setting up python3 (3.7.3-1) ...
running python rtupdate hooks for python3.7...
running python post-rtupdate hooks for python3.7...
Setting up python3.7-venv (3.7.3-2+deb10u3) ...
Setting up python3-lib2to3 (3.7.3-1) ...
Setting up python3-distutils (3.7.3-1) ...
Setting up python3-venv (3.7.3-1) ...
Setting up python3-pip (18.1-5) ...
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for mime-support (3.62) ...
Removing intermediate container 3a02c51e19bf
 ---> ec4b00581a8c
Step 5/23 : RUN apt-get clean
 ---> Running in 475548ffa8d4
Removing intermediate container 475548ffa8d4
 ---> b450e6aac1bd
Step 6/23 : ARG UID=1000
 ---> Running in f21b04689a7b
Removing intermediate container f21b04689a7b
 ---> 499e0ca92f6f
Step 7/23 : RUN useradd -m -u $UID apm-server
 ---> Running in ab92d0f6c447
Removing intermediate container ab92d0f6c447
 ---> e079a0e27859
Step 8/23 : USER $UID
 ---> Running in 2a2ea341b4f0
Removing intermediate container 2a2ea341b4f0
 ---> f96385e961d1
Step 9/23 : ENV HOME=/home/apm-server
 ---> Running in 68e7f01f00d4
Removing intermediate container 68e7f01f00d4
 ---> e11462c49ba4
Step 10/23 : ENV GOPATH=/go
 ---> Running in 90106afbe199
Removing intermediate container 90106afbe199
 ---> 6b411dde355f
Step 11/23 : ENV PYTHON_ENV /tmp/python-env
 ---> Running in 58240af9eb68
Removing intermediate container 58240af9eb68
 ---> c4ec0552c4c1
Step 12/23 : RUN python3 -m venv $PYTHON_ENV/build/ve/linux
 ---> Running in bdc494c7a559
Removing intermediate container bdc494c7a559
 ---> 216a162d2843
Step 13/23 : RUN $PYTHON_ENV/build/ve/linux/bin/pip install wheel
 ---> Running in bd4c9b7066c3
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.36.2
Removing intermediate container bd4c9b7066c3
 ---> af4459fdd3a3
Step 14/23 : RUN touch -d "Yesterday" $PYTHON_ENV/build/ve/linux/bin/activate
 ---> Running in 1b1078f9991c
Removing intermediate container 1b1078f9991c
 ---> 2e0725cf3ecf
Step 15/23 : WORKDIR $HOME
 ---> Running in 505598c9fa41
Removing intermediate container 505598c9fa41
 ---> b14d51f36321
Step 16/23 : COPY go.mod go.sum ./
 ---> 1dd50b029412
Step 17/23 : COPY approvaltest/go.mod approvaltest/go.sum ./approvaltest/
 ---> 7fb4c4397190
Step 18/23 : COPY systemtest/go.mod systemtest/go.sum ./systemtest/
 ---> 0a7d460c2ea6
Step 19/23 : COPY internal/otel_collector/go.mod internal/otel_collector/go.sum ./internal/otel_collector/
 ---> e649cab1019f
Step 20/23 : RUN go mod download
 ---> Running in 86c28b5ecc58
Removing intermediate container 86c28b5ecc58
 ---> bffaf604b3c7
Step 21/23 : RUN cd approvaltest && go mod download
 ---> Running in 63b0e623fe5d
Removing intermediate container 63b0e623fe5d
 ---> 6abdd2c2aad9
Step 22/23 : RUN cd systemtest && go mod download
 ---> Running in 28b07fdcd9eb
Removing intermediate container 28b07fdcd9eb
 ---> b17e958ca2f0
Step 23/23 : HEALTHCHECK CMD exit 0
 ---> Running in 6cfe4e839052
Removing intermediate container 6cfe4e839052
 ---> 40246cdc4155

Successfully built 40246cdc4155
Successfully tagged apm-server_beat:latest
WARNING: Image for service beat was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating apm-server_elasticsearch_1    ... done
Creating apm-server_package-registry_1 ... done
Creating apm-server_kibana_1           ... done

ERROR: for proxy_dep  Container "6518bf93b78c" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Just in case - kibana isn't running either:

```
$ docker-compose up kibana         
apm-server_package-registry_1 is up-to-date
apm-server_elasticsearch_1 is up-to-date
Starting apm-server_kibana_1 ... done
Attaching to apm-server_kibana_1
kibana_1            | {"type":"log","@timestamp":"2021-04-16T21:53:16+00:00","tags":["fatal","root"],"pid":936,"message":"ValidationError: [config validation of [xpack.fleet].agents.kibana]: definition for this key is missing\n    at ObjectType.validate (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:51:19)\n    at ConfigService.validateAtPath (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:170:23)\n    at MapSubscriber.project (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:177:166)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/kibana/node_modules/rxjs/internal/ReplaySubject.js:80:28)\n    at ReplaySubject.Observable._trySubscribe (/usr/share/kibana/node_modules/rxjs/internal/Observable.js:44:25)\n    at ReplaySubject.Subject._trySubscribe (/usr/share/kibana/node_modules/rxjs/internal/Subject.js:102:51)\n    at ReplaySubject.Observable.subscribe (/usr/share/kibana/node_modules/rxjs/internal/Observable.js:30:22)\n    at MapSubscriber.shareReplayOperation (/usr/share/kibana/node_modules/rxjs/internal/operators/shareReplay.js:48:32)\n    at Observable.subscribe (/usr/share/kibana/node_modules/rxjs/internal/Observable.js:25:31)\n    at MapOperator.call (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:32:23) {\n  cause: SchemaTypeError: definition for this key is missing\n      at ObjectType.onError (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:76:20)\n      at type.<anonymous> (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:41:53)\n      at finish (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:529:50)\n      at type._validate (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:618:24)\n      at type._base (/usr/share/kibana/node_modules/joi/lib/types/object/index.js:212:45)\n      at type._validate (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:614:37)\n      at type._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:674:29)\n      at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:146:23)\n      at ObjectType.validate (/usr/share/kibana/node_modules/@kbn/config-schema/target/types/type.js:46:72)\n      at ConfigService.validateAtPath (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:170:23)\n      at MapSubscriber.project (/usr/share/kibana/node_modules/@kbn/config/target/config_service.js:177:166)\n      at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n      at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n      at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n      at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n      at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26) {\n    cause: undefined,\n    path: [ 'agents', 'kibana' ]\n  }\n}"}
kibana_1            | 
kibana_1            |  FATAL  Error: [config validation of [xpack.fleet].agents.kibana]: definition for this key is missing
kibana_1            | 
apm-server_kibana_1 exited with code 1
```
Is it a bug or I'm doing something wrong?

**Comment by axw** [comment]
Thanks for opening the issue!

>Is it a bug or I'm doing something wrong?

You're not doing anything wrong. There were some changes to Kibana that we haven't yet compensated for. Should be fixed by https://github.com/elastic/apm-server/pull/5115.

In case you're not aware, the `docker-compose.yml` in this repo is intended for apm-server development, so it's not expected to be 100% stable. Just letting you know in case you intended to use it for other purposes.

**Comment by drnextgis** [comment]
@axw thanks for the prompt fix! After updating I'm getting another error:
```
docker-compose up beat
Starting apm-server_package-registry_1 ... done
Starting apm-server_elasticsearch_1    ... done
Starting apm-server_kibana_1           ... done
Starting apm-server_proxy_dep_1        ... done
Starting apm-server_beat_1             ... done
Attaching to apm-server_beat_1
beat_1              | go build github.com/elastic/apm-server/x-pack/apm-server: copying /tmp/go-build414706060/b001/exe/a.out: open apm-server: permission denied
beat_1              | make: *** [Makefile:40: apm-server] Error 1
apm-server_beat_1 exited with code 2
```

**Comment by axw** [comment]
@drnextgis I'm not sure why that would be, sorry. If you're just trying to run APM Server, I suggest using https://github.com/elastic/apm-integration-testing instead
