### ISSUE TITLE
panic when posting concurrent frontend transactions

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#517]
Found while investigating #515.  Easily reproducible by setting `apm-server.frontend.source_mapping.index_pattern` to one that doesn't match any existing ones and throwing a minimal amount of load when `apm-server.frontend.enabled=true`.  3 observations:

* does not manifest without concurrent requests
* crashes the entire process when requests are received during startup - `fatal error: concurrent map writes`
* crashes just the goroutine handling the request - `slice bounds out of range`

```
2018/01/17 19:07:38 http: panic serving 127.0.0.1:59427: runtime error: slice bounds out of range
goroutine 85 [running]:
net/http.(*conn).serve.func1(0xc420226640)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1697 +0xd0
panic(0x4ad0d80, 0x52e1da0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
bytes.(*Buffer).Write(0xc420172310, 0xc42050cd10, 0x1, 0x40, 0xc42050cd10, 0x1, 0x40)
	/usr/local/Cellar/go/1.9.2/libexec/src/bytes/buffer.go:165 +0xff
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json.writer.write(0x5291fc0, 0xc420172310, 0xc42050cd10, 0x1, 0x40, 0xc42050cd10, 0x1)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json/visitor.go:37 +0x4f
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json.(*Visitor).writeByte(0xc42050cd00, 0x22, 0x0, 0x0)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json/visitor.go:48 +0x5c
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json.(*Visitor).OnString(0xc42050cd00, 0x4c177cf, 0x4, 0xc4206fe400, 0x449a00f)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json/visitor.go:142 +0x55
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json.(*Visitor).OnKey(0xc42050cd00, 0x4c177cf, 0x4, 0xc4206fe460, 0xc4206fe450)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/json/visitor.go:88 +0x60
github.com/elastic/apm-server/vendor/github.com/urso/go-structform.(*extVisitor).OnKey(0xc4203b4340, 0x4c177cf, 0x4, 0x0, 0x0)
	<autogenerated>:1 +0x50
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype.foldMapInterface(0xc42041d1a0, 0x4ac4720, 0xc4202f7620, 0x5315520, 0x0)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype/fold_map.go:35 +0x13b
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype.foldInterfaceValue(0xc42041d1a0, 0x4ac4720, 0xc4202f7620, 0x0, 0x0)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype/fold.go:81 +0x291
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype.foldMapInterface(0xc42041d1a0, 0x4ac4720, 0xc4202f7710, 0x5315520, 0x52f4260)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype/fold_map.go:38 +0x16f
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype.foldInterfaceValue(0xc42041d1a0, 0x4ac4720, 0xc4202f7710, 0x0, 0xc4206fe5e8)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype/fold.go:81 +0x291
github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype.(*Iterator).Fold(0xc42041d1a0, 0x4ac4720, 0xc4202f7710, 0xc420472960, 0xc4206fe6e8)
	/go/src/github.com/elastic/apm-server/vendor/github.com/urso/go-structform/gotype/fold.go:69 +0x41
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*jsonEncoder).AddRaw(0xc42020d400, 0x4ac4720, 0xc4202f7710, 0x0, 0x0)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/enc.go:98 +0x140
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*jsonEncoder).Marshal(0xc42020d400, 0x4ac4720, 0xc4202f7710, 0x1ff, 0xc4206241a0)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/enc.go:87 +0x5a
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Connection).RequestURL(0xc4206feaf8, 0x4c17137, 0x3, 0xc420472960, 0x23, 0x4ac4720, 0xc4202f7710, 0xc420472960, 0x23, 0xc420693cc0, ...)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:722 +0x6c
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Connection).Request(0xc4206feaf8, 0x4c17137, 0x3, 0xc420429390, 0xe, 0x0, 0x0, 0x0, 0x4ac4720, 0xc4202f7710, ...)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:709 +0x299
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Connection).apiCall(0xc4206feaf8, 0x4c17137, 0x3, 0x4c181c4, 0x5, 0x0, 0x0, 0x4c1a101, 0x7, 0x0, ...)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/api.go:212 +0x160
github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Connection).SearchURIWithBody(0xc4206feaf8, 0x4c181c4, 0x5, 0x0, 0x0, 0x0, 0x4ac4720, 0xc4202f7710, 0x403663f, 0xc420538600, ...)
	/go/src/github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/api.go:182 +0xd7
github.com/elastic/apm-server/sourcemap.(*smapElasticsearch).runESQuery(0xc42041d200, 0xc4202f7710, 0xc420160347, 0x5, 0xc420530680)
	/go/src/github.com/elastic/apm-server/sourcemap/elasticsearch.go:45 +0x169
github.com/elastic/apm-server/sourcemap.(*smapElasticsearch).fetch(0xc42041d200, 0xc420160304, 0xc, 0xc420160347, 0x5, 0xc420530680, 0x3c, 0x0, 0x4b5e900, 0x37)
	/go/src/github.com/elastic/apm-server/sourcemap/elasticsearch.go:34 +0x59
github.com/elastic/apm-server/sourcemap.(*SmapAccessor).Fetch(0xc420346980, 0xc420160304, 0xc, 0xc420160347, 0x5, 0xc420530680, 0x3c, 0x3c, 0x27, 0xc420018395)
	/go/src/github.com/elastic/apm-server/sourcemap/accessor.go:55 +0xf5
github.com/elastic/apm-server/sourcemap.(*SmapMapper).Apply(0xc42020d4d0, 0xc420160304, 0xc, 0xc420160347, 0x5, 0xc420530680, 0x3c, 0x1, 0x12, 0x0, ...)
	/go/src/github.com/elastic/apm-server/sourcemap/mapper.go:42 +0x68
github.com/elastic/apm-server/model.(*StacktraceFrame).applySourcemap(0xc42033e140, 0x5299140, 0xc42020d4d0, 0xc420160304, 0xc, 0xc42016c460, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/apm-server/model/stacktrace_frame.go:90 +0x135
github.com/elastic/apm-server/model.Stacktrace.sourcemapAndTransform(0xc42016d230, 0x2, 0x2, 0xc420346c40, 0xc420160304, 0xc, 0xc42016c460, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/apm-server/model/stacktrace.go:54 +0x156
github.com/elastic/apm-server/model.Stacktrace.Transform(0xc42016d230, 0x2, 0x2, 0xc420346c40, 0xc420160304, 0xc, 0xc42016c460, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/apm-server/model/stacktrace.go:14 +0xfb
github.com/elastic/apm-server/processor/transaction.(*Span).Transform(0xc4202288a0, 0xc420346c40, 0xc420160304, 0xc, 0xc42016c460, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/apm-server/processor/transaction/span.go:49 +0x44a
github.com/elastic/apm-server/processor/transaction.(*Span).Mappings.func2(0xc4201586c0)
	/go/src/github.com/elastic/apm-server/processor/transaction/span.go:33 +0x5d
github.com/elastic/apm-server/processor.CreateDoc(0x28973c40, 0xed1bc8225, 0x0, 0xc420136700, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/apm-server/processor/processor.go:30 +0xe9
github.com/elastic/apm-server/processor/transaction.(*payload).transform(0xc42033e000, 0xc420346c40, 0xc420158030, 0x0, 0x0)
	/go/src/github.com/elastic/apm-server/processor/transaction/payload.go:35 +0x357
github.com/elastic/apm-server/processor/transaction.(*processor).Transform(0xc42016c060, 0x4ac4720, 0xc420158030, 0x0, 0xc42063f8f8, 0x4013778, 0x10, 0x4a7bb60)
	/go/src/github.com/elastic/apm-server/processor/transaction/processor.go:61 +0x13b
github.com/elastic/apm-server/beater.processRequest(0xc4203c8000, 0x4c69a58, 0xc420346c40, 0xc42020cde0, 0xc4201b71e0, 0xc42021d528, 0xc42063f978, 0x4297fd3)
	/go/src/github.com/elastic/apm-server/beater/handlers.go:326 +0x117
github.com/elastic/apm-server/beater.processRequestHandler.func1(0x529c440, 0xc420346000, 0xc4203c8000)
	/go/src/github.com/elastic/apm-server/beater/handlers.go:305 +0x53
net/http.HandlerFunc.ServeHTTP(0xc42041d530, 0x529c440, 0xc420346000, 0xc4203c8000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x44
github.com/elastic/apm-server/beater.corsHandler.func2(0x529c440, 0xc420346000, 0xc4203c8000)
	/go/src/github.com/elastic/apm-server/beater/handlers.go:295 +0x36f
net/http.HandlerFunc.ServeHTTP(0xc420346ce0, 0x529c440, 0xc420346000, 0xc4203c8000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x44
github.com/elastic/apm-server/beater.ipRateLimitHandler.func2(0x529c440, 0xc420346000, 0xc4203c8000)
	/go/src/github.com/elastic/apm-server/beater/handlers.go:196 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420346d60, 0x529c440, 0xc420346000, 0xc4203c8000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x44
github.com/elastic/apm-server/beater.killSwitchHandler.func1(0x529c440, 0xc420346000, 0xc4203c8000)
	/go/src/github.com/elastic/apm-server/beater/handlers.go:172 +0x59
net/http.HandlerFunc.ServeHTTP(0xc420346d80, 0x529c440, 0xc420346000, 0xc4203c8000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x44
github.com/elastic/apm-server/beater.logHandler.func1(0x52a43c0, 0xc4203e02a0, 0xc420507000)
	/go/src/github.com/elastic/apm-server/beater/handlers.go:154 +0x263
net/http.HandlerFunc.ServeHTTP(0xc420346da0, 0x52a43c0, 0xc4203e02a0, 0xc420507000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42041cb70, 0x52a43c0, 0xc4203e02a0, 0xc420507000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc42050cf70, 0x52a43c0, 0xc4203e02a0, 0xc420507000)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420226640, 0x52a5200, 0xc420212040)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2720 +0x288
```

**Comment by graphaelli** [comment]
> crashes the entire process when requests are received during startup - fatal error: concurrent map writes

happens regardless of `index_pattern` but only when frontend is enabled.

**Comment by graphaelli** [comment]
https://github.com/elastic/apm-server/compare/master...graphaelli:issue-517 is a rough implementation of a URI search for sourcemaps.  Through audit and load testing I was unable to find concurrency safety issues or reproduce the panic.  @elastic/apm-server if seems reasonable we'll need to tighten that code up, add tests for values that url encode strangely, etc.

Otherwise, implementing locking around client access shouldn't be too tough.

**Comment by graphaelli** [comment]
closing this as a fix is for this specific panic.  We can revisit as an enhancement if needed.
