### ISSUE TITLE
[systemtest] flaky test error index out of range [0] with length 0 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5494]
Running `systemtests` locally on macOS leads to following flaky test result:

```
go test ./...

apm-server_package-registry_1 is up-to-date
apm-server_elasticsearch_1 is up-to-date
apm-server_kibana_1 is up-to-date
apm-server_fleet-server_1 is up-to-date
Docker Compose is now in the Docker CLI, try `docker compose up`

2021/06/18 12:08:30 Building apm-server...
2021/06/18 12:08:45 Built /Users/simitt/coding/go/elastic/apm-server/apm-server
2021/06/18 12:11:19 Building image elastic-agent-systemtest:8.0.0-943ef2c0-SNAPSHOT...
2021/06/18 12:11:19 Building apm-server...
2021/06/18 12:11:31 Built /Users/simitt/coding/go/elastic/apm-server/build/apm-server-linux
2021/06/18 12:11:45 Built image elastic-agent-systemtest:8.0.0-943ef2c0-SNAPSHOT
2021/06/18 12:11:45 Starting container id: c36abc256b31 image: quay.io/testcontainers/ryuk:0.2.3
2021/06/18 12:11:49 Waiting for container id c36abc256b31 image: quay.io/testcontainers/ryuk:0.2.3
2021/06/18 12:11:49 Container is ready id: c36abc256b31 image: quay.io/testcontainers/ryuk:0.2.3
2021/06/18 12:11:51 Starting container id: af3c45db2a0f image: elastic-agent-systemtest:8.0.0-943ef2c0-SNAPSHOT
2021/06/18 12:12:00 Waiting for container id af3c45db2a0f image: elastic-agent-systemtest:8.0.0-943ef2c0-SNAPSHOT
--- FAIL: TestFleetIntegration (62.11s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1545 [running]:
testing.tRunner.func1.2(0x4e51420, 0xc000692708)
	/Users/simitt/.gvm/versions/go1.16.5.darwin.amd64/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc0005bdc80)
	/Users/simitt/.gvm/versions/go1.16.5.darwin.amd64/src/testing/testing.go:1146 +0x4b6
panic(0x4e51420, 0xc000692708)
	/Users/simitt/.gvm/versions/go1.16.5.darwin.amd64/src/runtime/panic.go:965 +0x1b9
github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort(0xc000044300, 0x5074670, 0xc000110000, 0x4f0b170, 0x8, 0x0, 0x0, 0x3132303200000000, 0x72)
	/Users/simitt/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:135 +0x485
github.com/testcontainers/testcontainers-go/wait.(*HTTPStrategy).WaitUntilReady(0xc000226150, 0x50746e0, 0xc000110000, 0x50749f0, 0xc000044300, 0x0, 0x0)
	/Users/simitt/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/wait/http.go:127 +0x167
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc000044300, 0x50746e0, 0xc001b4c060, 0x0, 0x0)
	/Users/simitt/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:167 +0x315
github.com/elastic/apm-server/systemtest.(*ElasticAgentContainer).Start(0xc00029ce00, 0x0, 0x0)
	/Users/simitt/coding/go/elastic/apm-server/systemtest/containers.go:378 +0x243
github.com/elastic/apm-server/systemtest_test.TestFleetIntegration(0xc0005bdc80)
	/Users/simitt/coding/go/elastic/apm-server/systemtest/fleet_test.go:82 +0x616
testing.tRunner(0xc0005bdc80, 0x4f47c40)
	/Users/simitt/.gvm/versions/go1.16.5.darwin.amd64/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/Users/simitt/.gvm/versions/go1.16.5.darwin.amd64/src/testing/testing.go:1238 +0x2b3
FAIL	github.com/elastic/apm-server/systemtest	230.080s
```

**Comment by marclop** [comment]
@simitt I did experience this myself a few weeks ago, but I can't seem to reproduce it now, it might've been tied to the version of `testcontainers-go` we were using at the time, should we close this one and reopen if we see it happening again?

**Comment by simitt** [comment]
Cannot reproduce the issue any more - closing out this issue.
