### ISSUE TITLE
Global label sanitisation may lead to concurrent map modification/access

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#8651]
**APM Server version** (`apm-server version`): 7.17.1

**Description of the problem including expected versus actual behavior**:

Server panics, e.g.

```
Jun 21 03:44:25 rn000043550 apm-server[71111]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 21 03:44:25 rn000043550 apm-server[71111]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x561e096719d1]
Jun 21 03:44:25 rn000043550 apm-server[71111]: goroutine 197 [running]:
Jun 21 03:44:25 rn000043550 apm-server[71111]: github.com/elastic/apm-server/model.sanitizeLabels(0xc00e831d50)
Jun 21 03:44:25 rn000043550 apm-server[71111]: #011/go/src/github.com/elastic/apm-server/model/labels.go:35 +0x118
Jun 21 03:44:25 rn000043550 apm-server[71111]: github.com/elastic/apm-server/model.(*APMEvent).BeatEvent(0xc00e8318a8, {0xc00afa6ec0, 0xc00e831828})
--
Jun 21 05:55:29 rn000043550 apm-server[82942]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 21 05:55:29 rn000043550 apm-server[82942]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x561df7a1f9d1]
Jun 21 05:55:29 rn000043550 apm-server[82942]: goroutine 224 [running]:
Jun 21 05:55:29 rn000043550 apm-server[82942]: github.com/elastic/apm-server/model.sanitizeLabels(0xc011b9dd50)
Jun 21 05:55:29 rn000043550 apm-server[82942]: #011/go/src/github.com/elastic/apm-server/model/labels.go:35 +0x118
Jun 21 05:55:29 rn000043550 apm-server[82942]: github.com/elastic/apm-server/model.(*APMEvent).BeatEvent(0xc011b9d8a8, {0xc01167ec40, 0xc011b9d828})
--
Jun 21 05:57:40 rn000043550 apm-server[89635]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 21 05:57:40 rn000043550 apm-server[89635]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x558e90b2a5c1]
Jun 21 05:57:40 rn000043550 apm-server[89635]: goroutine 61 [running]:
Jun 21 05:57:40 rn000043550 apm-server[89635]: github.com/elastic/apm-server/model.sanitizeLabels(0xc007afdd50)
Jun 21 05:57:40 rn000043550 apm-server[89635]: #011/go/src/github.com/elastic/apm-server/model/labels.go:31 +0x17b
Jun 21 05:57:40 rn000043550 apm-server[89635]: github.com/elastic/apm-server/model.(*APMEvent).BeatEvent(0xc007afd8a8, {0xc0027c58a0, 0x558e90e47585})
--
Jun 21 10:12:53 rn000043550 apm-server[113640]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 21 10:12:53 rn000043550 apm-server[113640]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55673b8fa9d1]
Jun 21 10:12:53 rn000043550 apm-server[113640]: goroutine 216 [running]:
Jun 21 10:12:53 rn000043550 apm-server[113640]: github.com/elastic/apm-server/model.sanitizeLabels(0xc011b53d50)
Jun 21 10:12:53 rn000043550 apm-server[113640]: #011/go/src/github.com/elastic/apm-server/model/labels.go:35 +0x118
Jun 21 10:12:53 rn000043550 apm-server[113640]: github.com/elastic/apm-server/model.(*APMEvent).BeatEvent(0xc011b538a8, {0xc001394500, 0xc011b53828})
```

I've tracked this down to global labels being shared by multiple events in 7.17, when there are no event-specific labels. If the global labels need sanitisation, then there will be concurrent map accesses. The shared label map should be cloned before sanitisation, to avoid concurrent modification.

**Steps to reproduce**:

 1. Send a continuous stream of events with global labels that require sanitisation (e.g. a label key with a dot in it), and no event-specific labels.
 2. Eventually, the server will panic.

(It may take a while, depends on timing.)

**Comment by axw** [comment]
Closed by https://github.com/elastic/apm-server/pull/8652
