### ISSUE TITLE
Inappropriate use of regexProperties in spec?

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#909]
I'm running [go-fuzz](https://github.com/dvyukov/go-fuzz), with the program in this gist: https://gist.github.com/axw/55d4eeaf4055ee17a47b381eed62b0fb. In short, I unmarshal the data into a payload structure, remarshal it using the custom JSON encoding logic, and then validate the output using apm-server/transactions/NewProcessor.

The following input
```
{"service":{"agent":{"name":"","version":""},"name":"0"},"transactions":[{"duration":0,"id":"00000000-0000-0000-0000-000000000000","type":"","context":{"cuStom":{"(":true}}}]}
```
causes this validation error
```
panic: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
  I[#/transactions/0/context/custom] S[#/properties/transactions/items/properties/context/properties/custom] patternProperty "(" is not valid regex

goroutine 1 [running]:
github.com/elastic/apm-agent-go/model.Fuzz(0x7f94dccb1000, 0xaf, 0x200000, 0xc3f20c)
	/tmp/go-fuzz-build804586361/gopath/src/github.com/elastic/apm-agent-go/model/gofuzz.go:74 +0x6e2
go-fuzz-dep.Main(0xc49ee0)
	/tmp/go-fuzz-build804586361/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
	/tmp/go-fuzz-build804586361/gopath/src/github.com/elastic/apm-agent-go/model/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

While it's undoubtedly weird to use "(" as a custom context key, I don't think using regexProperties is an appropriate way to validate it. That would prevent `"("`, but not `"\\("`, for example.

**Comment by graphaelli** [comment]
@axw I must have missed something here, the input provided didn't throw a validation error on the various commits I tried.  2665a0d2029a31ec41fd3d5cd214e38f0c9d7536 was a big one since this issue was opened but I don't think this part of the spec was touched.  Can you help me reproduce this as I don't understand the issue currently.

**Comment by axw** [comment]
```go
package main                                    
                                                
import "github.com/elastic/apm-agent-go"        
                                                
func main() {                                   
        t := elasticapm.DefaultTracer           
        tx := t.StartTransaction("name", "type")
        tx.Context.SetCustom("(", true)         
        tx.End()                                
        t.Flush(nil)                            
}                                               
```

```sh
$ ELASTIC_APM_DEBUG=tracetransport=1 go run foo.go

2018/07/17 09:44:12 elasticapm SendTransactions 1 -> &model.TransactionsPayload{
    Service: &model.Service{
        Name:        "foo",
        Version:     "",
        Environment: "",
        Agent:       model.Agent{Name:"go", Version:"0.4.0"},
        Framework:   (*model.Framework)(nil),
        Language:    &model.Language{Name:"go", Version:"go1.10.3"},
        Runtime:     &model.Runtime{Name:"gc", Version:"go1.10.3"},
    },
    Process: &model.Process{
        Pid:   30700,
        Ppid:  &int(30604),
        Title: "foo",
        Argv:  {"/tmp/go-build373134223/b001/exe/foo"},
    },
    System:       &model.System{Architecture:"amd64", Hostname:"alloy", Platform:"linux"},
    Transactions: {
        {
            ID:        {0x6b, 0x8d, 0x3a, 0x87, 0x75, 0x52, 0x42, 0xbb, 0xf9, 0xcc, 0xa3, 0xe7, 0x7e, 0x5f, 0x5a, 0x30},
            Name:      "name",
            Type:      "type",
            Timestamp: model.Time{
                wall: 0xb4efb13,
                ext:  63667388652,
                loc:  (*time.Location)(nil),
            },
            Duration: 0.000836,
            Result:   "",
            Context:  &model.Context{
                Request:  (*model.Request)(nil),
                Response: (*model.Response)(nil),
                User:     (*model.User)(nil),
                Custom:   {
                    {
                        Key:   "(",
                        Value: bool(true),
                    },
                },
                Tags: {},
            },
            Sampled:   (*bool)(nil),
            SpanCount: model.SpanCount{},
            Spans:     nil,
        },
    },
}
2018/07/17 09:44:12 elasticapm SendTransactions 1 <- SendTransactions failed with 400 Bad Request: data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
  I[#/transactions/0/context/custom] S[#/properties/transactions/items/properties/context/properties/custom] patternProperty "(" is not valid regex
```

**Comment by graphaelli** [comment]
Thanks @axw - turns out that capital `S` in `cuStom` in the original report prevented the reproduction. , didn't notice that until comparing payload between the reproduction cases.

**Comment by axw** [comment]
> Thanks @axw - turns out that capital S in cuStom in the original report prevented the reproduction. , didn't notice that until comparing payloads between the reproduction cases.

Ah, right. In the go-fuzz program, I'm decoding that payload into a struct, and encoding/json will match the field names to object keys case-insensitively. That "cuStom" would have been re-encoded as "custom" on the way out.
